import Vue from 'vue'
import {
  Rate,Breadcrumb, BreadcrumbItem, Loading, Link, Image, Button, Container, Header, Main, Input, Aside, Radio, Footer, Form, FormItem, Steps, Step, Message, Select, Option, Table, TableColumn,
  MessageBox, Row, Menu, MenuItem, Col, Avatar, Tabs, TabPane, Submenu, MenuItemGroup, Upload, Dialog, TimeSelect, Cascader, RadioGroup,
  Pagination, Backtop, Divider, Carousel, CarouselItem, DatePicker, Dropdown, DropdownItem, DropdownMenu, Card, Tooltip
} from 'element-ui'

import 'element-ui/lib/theme-chalk/index.css'
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
Vue.use(Loading)
Vue.use(Rate)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Link)
Vue.use(Image)
Vue.use(Button)
Vue.use(Container)
Vue.use(Header)
Vue.use(Main)
Vue.use(Input)
Vue.use(Aside)
Vue.use(Radio)
Vue.use(Footer)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Steps)
Vue.use(Step)
Vue.use(Row)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Col)
Vue.use(Avatar)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(MenuItemGroup)
Vue.use(Submenu)
Vue.use(Upload)
Vue.use(Dialog)
Vue.use(TimeSelect)
Vue.use(Cascader)
Vue.use(RadioGroup)
Vue.use(Select)
Vue.use(Option)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Pagination)
Vue.use(Backtop)
Vue.use(Divider)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(DatePicker)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.use(Card)
Vue.use(Tooltip)